spring.application.name=enrichmentService
server.port=8010

# Logging Level
logging.level.root=INFO
logging.level.com.bankguard.enrichmentservice=DEBUG
# External service URLs
external.alertcase-service.url=http://localhost:8085

