spring.application.name=sarReport


spring.datasource.url=jdbc:mysql://localhost:3306/report?useSSL=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8088

# This sets the URL where you will view the Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
# This sets the URL for the raw JSON documentation
#springdoc.api-docs.path=/v3/api-docs
