server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:raj-singh-23/config-server.git
          default-label: main                          # branch name (main)