# Application Identity
spring.application.name=apiGateway
server.port=1001

# Force reactive mode (important for Spring Cloud Gateway)
spring.main.web-application-type=reactive

# ===============================
# Transaction Service Route (Updated Prefix)
# ===============================
spring.cloud.gateway.server.webflux.routes[0].id=transaction-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8089
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/transaction/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1


# Suspicious Activity Report Service Route (Updated Prefix)
# ===============================
spring.cloud.gateway.server.webflux.routes[1].id=sar-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8088
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/generate/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1


# Suspicious Activity Report Service Route (Updated Prefix)
# ===============================
spring.cloud.gateway.server.webflux.routes[2].id=alertcase-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8085
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/msg/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=1

# ===============================
# Logging (VERY useful for debugging)
# ===============================
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=INFO

